name: chat-langchain

dependencies:
- python=3.10.9
- pip:
  - openai
  - fastapi
  - black
  - isort
  - websockets
  - pydantic
  - langchain==0.0.156
  - uvicorn
  - jinja2
  - faiss-cpu
  - bs4
  - unstructured
  - libmagic
